* More cleanups. * Updated alltools. * botchk works now.

diff --git a/scripts/botchk b/scripts/botchk
--- a/scripts/botchk
+++ b/scripts/botchk
@@ -1,11 +1,9 @@
 #! /bin/sh
 #
-# botchk
+# $Id: botchk,v 1.7 2003/12/17 00:58:02 wcc Exp $
 #
-# $Id: botchk,v 1.6 2002/04/16 22:40:59 ite Exp $
-#
-# This is a script suitable for use in a crontab.  It checks to make sure
-# your bot is running.  YOU NEED A SEPARATE CRON JOB FOR EACH BOT.  If your
+# This is a script suitable for use in a crontab. It checks to make sure
+# your bot is running. YOU NEED A SEPARATE CRON JOB FOR EACH BOT. If your
 # bot isn't found, it'll try to start it back up.
 #
 # You'll need to edit this script for your bot.
@@ -18,86 +16,59 @@
 #    0,10,20,30,40,50 * * * *   /home/mydir/mybot/botchk >/dev/null 2>&1
 #
 
-# change this to the directory you run your bot from (capitalization COUNTS):
+# Change this to the directory you run your bot from (capitalization COUNTS):
 botdir="/home/mydir/mybot"
 
-# change this to the name of your bot's config file (capitalization COUNTS):
-botscript="mybot"
+# Change this to the name of your bot's config file (capitalization COUNTS):
+botconfig="config.xml"
 
-# change this to the botnet-nick of your bot (capitalization COUNTS):
-botname="LamestBot"
+# change this to the botname of your bot (capitalization COUNTS):
+botname="eggdrop"
 
 # change this to the name of your bot's userfile (capitalization COUNTS):
-userfile="LamestBot.user"
-
-# change this to the name of your bot's pidfile (capitalization COUNTS):
-pidfile="pid.LamestBot"
+userfile="users.xml"
 
 ########## you probably don't need to change anything below here ##########
 
 cd $botdir
 
-# is there a pid file?
-if test -r $pidfile
-then
-  # there is a pid file -- is it current?
-  botpid=`cat $pidfile`
-  if `kill -CHLD $botpid >/dev/null 2>&1`
-  then
-    # it's still going -- back out quietly
-    exit 0
-  fi
-  echo ""
-  echo "Stale $pidfile file, erasing..."
-  rm -f $pidfile
+# Is there a pid file?
+if test -r pid.$botname; then
+        # There is a pid file -- is it current?
+        botpid=`cat pid.$botname`
+        if `kill -CHLD $botpid >/dev/null 2>&1`; then
+                # Yes.
+                exit 0
+        fi
+        echo ""
+        echo "Stale pid.$botname file, erasing..."
+        rm -f pid.$botname
 fi
 
-if test -r CANTSTART.$botname
-then
-  if test -r $userfile || test -r $userfile~new || test -r $userfile~bak
-  then
-    echo ""
-    echo "Userfile found, removing check file 'CANTSTART.$botname'..."
-    rm -f CANTSTART.$botname
-  fi
+if test -r CANTSTART.$botname; then
+        if test -r $userfile; then
+                echo ""
+                echo "Userfile found, removing check file 'CANTSTART.$botname'..."
+                rm -f CANTSTART.$botname
+        fi
 fi
 
-# test if we have run botchk previously and didn't find a userfile
-if test ! -f CANTSTART.$botname
-then
-  echo ""
-  echo "Couldn't find bot '$botname' running, reloading..."
-  echo ""
-  # check for userfile and reload bot if found
-  if test -r $userfile
-  then
-    # It's there, load the bot
-    ./$botscript
-    exit 0
-  else
-    if test -r $userfile~new
-    then
-      # Bot f*@!ed up while saving the userfile last time.  Move it over.
-      echo "Userfile missing.  Using last saved userfile..."
-      mv -f $userfile~new $userfile
-      ./$botscript
-      exit 0
-    else
-      if test -r $userfile~bak
-      then
-        # Userfile is missing, use backup userfile.
-        echo "Userfile missing.  Using backup userfile..."
-        cp -f $userfile~bak $userfile
-        ./$botscript
-        exit 0
-      else
-        # Well, nothing to work with...
-        echo "No userfile.  Could not reload the bot..."
-        echo "no userfile" > CANTSTART.$botname
-        exit 1
-      fi
-    fi
-  fi
+# Test if we have run botchk previously and didn't find a userfile.
+if test ! -f CANTSTART.$botname; then
+        echo ""
+        echo "Couldn't find bot '$botname' running, reloading..."
+        echo ""
+        # Check for userfile and reload bot if found.
+        if test -r $userfile; then
+                # It's there, load the bot.
+                ./eggdrop $botconfig
+                exit 0
+        else
+                # No userfile.
+                echo "No userfile.  Could not reload the bot..."
+                echo "No userfile." > CANTSTART.$botname
+                exit 1
+        fi
 fi
 
 exit 0
